language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kirillyershov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kirillyershov/docker-react npm run test -- --covarage
